[tool.poetry]
name = "pepper"
version = "0.1.0"
description = ""
authors = ["SSmJaE <shaoxydd8888@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sanic = "^20.12.2"
inflection = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
demo = "python ./demo/demo.py"
