[tool.poetry]
name = "pepperbot"
version = "0.1.2"
description = ""
authors = ["SSmJaE <shaoxydd8888@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
arrow = "^1.0.3"
pydantic = "^1.8.1"
devtools = "^0.6.1"
loguru = "^0.5.3"
pretty-errors = "^1.2.20"
APScheduler = "^3.7.0"
httpx = "^0.21.1"
sanic = "^21.9.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = { version = "^21.4b2", allow-prereleases = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
test = "pytest"
run = "python private/run.py"
