[
    // 群消息
    {
        event: "EventGroupMsg",
        robot_wxid: "wxid_adgwlc0cyazt22",
        robot_name: "",
        type: 1,
        from_wxid: "19521241254@chatroom",
        from_name: "",
        final_from_wxid: "wxid_opwzinl7jovm21",
        final_from_name: "SSmJaE",
        to_wxid: "wxid_adgwlc0cyazt22",
        msg: "八戒你把这个群屏蔽了吧",
    },
    // 合并转发
    {
        event: "EventGroupMsg",
        robot_wxid: "wxid_adgwlc0cyazt22",
        robot_name: "",
        type: 49,
        from_wxid: "19521241254@chatroom",
        from_name: "",
        final_from_wxid: "wxid_opwzinl7jovm21",
        final_from_name: "SSmJaE",
        to_wxid: "wxid_adgwlc0cyazt22",
        msg: '<?xml version="1.0"?>\r\n',
        //             '<msg>\r\n'
        //             '\t<appmsg appid="" sdkver="0">\r\n'
        //             '\t\t<title>群聊的聊天记录</title>\r\n'
        //             '\t\t<des>胖妞:啥\r\n'
        //             '胖妞:好</des>\r\n'
        //             '\t\t<username />\r\n'
        //             '\t\t<action>view</action>\r\n'
        //             '\t\t<type>19</type>\r\n'
        //             '\t\t<showtype>0</showtype>\r\n'
        //             '\t\t<content />\r\n'
        //             '\t\t<url>https://support.weixin.qq.com/cgi-bin/mmsupport-bin/readtemplate?t=page/favorite_record__w_unsuppo'
        //             'rt&amp;from=singlemessage&amp;isappinstalled=0</url>\r\n'
        //             '\t\t<lowurl />\r\n'
        //             '\t\t<forwardflag>0</forwardflag>\r\n'
        //             '\t\t<dataurl />\r\n'
        //             '\t\t<lowdataurl />\r\n'
        //             '\t\t<contentattr>0</contentattr>\r\n'
        //             '\t\t<streamvideo>\r\n'
        //             '\t\t\t<streamvideourl />\r\n'
        //             '\t\t\t<streamvideototaltime>0</streamvideototaltime>\r\n'
        //             '\t\t\t<streamvideotitle />\r\n'
        //             '\t\t\t<streamvideowording />\r\n'
        //             '\t\t\t<streamvideoweburl />\r\n'
        //             '\t\t\t<streamvideothumburl />\r\n'
        //             '\t\t\t<streamvideoaduxinfo />\r\n'
        //             '\t\t\t<streamvideopublishid />\r\n'
        //             '\t\t</streamvideo>\r\n'
        //             '\t\t<canvasPageItem>\r\n'
        //             '\t\t\t<canvasPageXml><![CDATA[]]></canvasPageXml>\r\n'
        //             '\t\t</canvasPageItem>\r\n'
        //             '\t\t<recorditem>&lt;recordinfo&gt;&lt;title&gt;群聊的聊天记录&lt;/title&gt;&lt;desc&gt;胖妞:啥&amp;#x0A;
        // 胖妞:好&lt;/desc'
        //             "&gt;&lt;datalist count='2'&gt;&lt;dataitem datatype='1' datasourceid='5298075291326845125'&gt;&lt;datades"
        //             'c&gt;啥&lt;/datadesc&gt;&lt;sourcename&gt;胖妞
        // &lt;/sourcename&gt;&lt;sourcetime&gt;2022-01-27&amp;#x20;15:49'
        //             ':41&lt;/sourcetime&gt;&lt;dataitemsource&gt;&lt;realchatname&gt;wxid_rqn31uwmjug922&lt;/realchatname&gt;&'
        //             "lt;/dataitemsource&gt;&lt;/dataitem&gt;&lt;dataitem datatype='1' datasourceid='3688838082895356808'&gt;&l"
        //             't;datadesc&gt;好&lt;/datadesc&gt;&lt;sourcename&gt;胖妞&lt;/sourcename&gt;&lt;sourcetime&gt;2022-01-27&amp;#'
        //             'x20;15:49:42&lt;/sourcetime&gt;&lt;dataitemsource&gt;&lt;realchatname&gt;wxid_rqn31uwmjug922&lt;/realchat'
        //             'name&gt;&lt;/dataitemsource&gt;&lt;/dataitem&gt;&lt;/datalist&gt;&lt;favusername&gt;wxid_opwzinl7jovm21&l'
        //             't;/favusername&gt;&lt;/recordinfo&gt;</recorditem>\r\n'
        //             '\t\t<appattach>\r\n'
        //             '\t\t\t<totallen>0</totallen>\r\n'
        //             '\t\t\t<attachid />\r\n'
        //             '\t\t\t<cdnattachurl />\r\n'
        //             '\t\t\t<emoticonmd5></emoticonmd5>\r\n'
        //             '\t\t\t<aeskey></aeskey>\r\n'
        //             '\t\t\t<fileext />\r\n'
        //             '\t\t\t<islargefilemsg>0</islargefilemsg>\r\n'
        //             '\t\t</appattach>\r\n'
        //             '\t\t<extinfo />\r\n'
        //             '\t\t<androidsource>0</androidsource>\r\n'
        //             '\t\t<thumburl />\r\n'
        //             '\t\t<mediatagname />\r\n'
        //             '\t\t<messageaction><![CDATA[]]></messageaction>\r\n'
        //             '\t\t<messageext><![CDATA[]]></messageext>\r\n'            '\t\t<emoticongift>\r\n'
        //             '\t\t\t<packageflag>0</packageflag>\r\n'
        //             '\t\t\t<packageid />\r\n'
        //             '\t\t</emoticongift>\r\n'
        //             '\t\t<emoticonshared>\r\n'
        //             '\t\t\t<packageflag>0</packageflag>\r\n'
        //             '\t\t\t<packageid />\r\n'
        //             '\t\t</emoticonshared>\r\n'
        //             '\t\t<designershared>\r\n'
        //             '\t\t\t<designeruin>0</designeruin>\r\n'
        //             '\t\t\t<designername>null</designername>\r\n'
        //             '\t\t\t<designerrediretcturl>null</designerrediretcturl>\r\n'
        //             '\t\t</designershared>\r\n'
        //             '\t\t<emotionpageshared>\r\n'
        //             '\t\t\t<tid>0</tid>\r\n'
        //             '\t\t\t<title>null</title>\r\n'
        //             '\t\t\t<desc>null</desc>\r\n'
        //             '\t\t\t<iconUrl>null</iconUrl>\r\n'
        //             '\t\t\t<secondUrl>null</secondUrl>\r\n'
        //             '\t\t\t<pageType>0</pageType>\r\n'
        //             '\t\t</emotionpageshared>\r\n'
        //             '\t\t<webviewshared>\r\n'
        //             '\t\t\t<shareUrlOriginal />\r\n'
        //             '\t\t\t<shareUrlOpen />\r\n'
        //             '\t\t\t<jsAppId />\r\n'
        //             '\t\t\t<publisherId />\r\n'
        //             '\t\t</webviewshared>\r\n'
        //             '\t\t<template_id />\r\n'
        //             '\t\t<md5 />\r\n'
        //             '\t\t<weappinfo>\r\n'
        //             '\t\t\t<username />\r\n'
        //             '\t\t\t<appid />\r\n'
        //             '\t\t\t<appservicetype>0</appservicetype>\r\n'
        //             '\t\t\t<secflagforsinglepagemode>0</secflagforsinglepagemode>\r\n'
        //             '\t\t\t<videopageinfo>\r\n'
        //             '\t\t\t\t<thumbwidth>0</thumbwidth>\r\n'
        //             '\t\t\t\t<thumbheight>0</thumbheight>\r\n'
        //             '\t\t\t\t<fromopensdk>0</fromopensdk>\r\n'
        //             '\t\t\t</videopageinfo>\r\n'
        //             '\t\t</weappinfo>\r\n'
        //             '\t\t<statextstr />\r\n'
        //             '\t\t<musicShareItem>\r\n'
        //             '\t\t\t<musicDuration>0</musicDuration>\r\n'
        //             '\t\t</musicShareItem>\r\n'
        //             '\t\t<finderLiveProductShare>\r\n'
        //             '\t\t\t<finderLiveID />\r\n'
        //             '\t\t\t<finderUsername />\r\n'
        //             '\t\t\t<finderObjectID />\r\n'
        //             '\t\t\t<finderNonceID />\r\n'
        //             '\t\t\t<liveStatus />\r\n'
        //             '\t\t\t<appId />\r\n'
        //             '\t\t\t<pagePath />\r\n'
        //             '\t\t\t<productId />\r\n'
        //             '\t\t\t<coverUrl />\r\n'
        //             '\t\t\t<productTitle />\r\n'
        //             '\t\t\t<marketPrice><![CDATA[0]]></marketPrice>\r\n'
        //             '\t\t\t<sellingPrice><![CDATA[0]]></sellingPrice>\r\n'
        //             '\t\t\t<platformHeadImg />\r\n'
        //             '\t\t\t<platformName />\r\n'
        //             '\t\t\t<shopWindowId />\r\n'
        //             '\t\t</finderLiveProductShare>\r\n'
        //             '\t\t<findernamecard>\r\n'
        //             '\t\t\t<username />\r\n'
        //             '\t\t\t<avatar><![CDATA[]]></avatar>\r\n'
        //             '\t\t\t<nickname />\r\n'
        //             '\t\t\t<auth_job />\r\n'
        //             '\t\t\t<auth_icon>0</auth_icon>\r\n'
        //             '\t\t\t<auth_icon_url />\r\n'
        //             '\t\t</findernamecard>\r\n'
        //             '\t\t<finderGuarantee>\r\n'
        //             '\t\t\t<scene><![CDATA[0]]></scene>\r\n'
        //             '\t\t</finderGuarantee>\r\n'
        //             '\t\t<directshare>0</directshare>\r\n'
        //             '\t\t<gamecenter>\r\n'
        //             '\t\t\t<namecard>\r\n'
        //             '\t\t\t\t<iconUrl />\r\n'
        //             '\t\t\t\t<name />\r\n'
        //             '\t\t\t\t<desc />\r\n'
        //             '\t\t\t\t<tail />\r\n'
        //             '\t\t\t\t<jumpUrl />\r\n'
        //             '\t\t\t</namecard>\r\n'
        //             '\t\t</gamecenter>\r\n'
        //             '\t\t<patMsg>\r\n'
        //             '\t\t\t<chatUser />\r\n'
        //             '\t\t\t<records>\r\n'
        //             '\t\t\t\t<recordNum>0</recordNum>\r\n'
        //             '\t\t\t</records>\r\n'
        //             '\t\t</patMsg>\r\n'
        //             '\t\t<secretmsg>\r\n'
        //             '\t\t\t<issecretmsg>0</issecretmsg>\r\n'
        //             '\t\t</secretmsg>\r\n'
        //             '\t\t<websearch>\r\n'
        //             '\t\t\t<rec_category>0</rec_category>\r\n'
        //             '\t\t\t<channelId>0</channelId>\r\n'
        //             '\t\t</websearch>\r\n'
        //             '\t</appmsg>\r\n'
        //             '\t<fromusername>wxid_opwzinl7jovm21</fromusername>\r\n'
        //             '\t<scene>0</scene>\r\n'
        //             '\t<appinfo>\r\n'
        //             '\t\t<version>1</version>\r\n'
        //             '\t\t<appname />\r\n'
        //             '\t</appinfo>\r\n'
        //             '\t<commenturl />\r\n'
        //             '</msg>\r\n'
    },
];
